
<?php 

return [
    'property_types' => [
        ['type_en' => 'apartment', 'type_ar' => 'شقق'],
        ['type_en' => 'building', 'type_ar' => 'مباني'],
        ['type_en' => 'chalet', 'type_ar' => 'شليه'],
        ['type_en' => 'furnished apartment', 'type_ar' => 'شقة حديثة'],
        ['type_en' => 'villa', 'type_ar' => 'فيلا'],
    ],
    //type_payments
    'type_payments' => [
        ['type_en' => 'cash', 'type_ar' => 'كاش'],
        ['type_en' => 'installments', 'type_ar' => 'تقسيط'],
    ],
    //type_finishes
    'type_finishes' => [
        ['type_en' => 'extra super lux', 'type_ar' => 'اكسترا سوبر لوكس'],
        ['type_en' => 'super lux', 'type_ar' => 'سوبر لوكس'],
        ['type_en' => 'lux', 'type_ar' => 'لوكس'],
        ['type_en' => 'semi finished', 'type_ar' => 'نصف تشطيب'],
        ['type_en' => 'no finished', 'type_ar' => 'من غير تشطيب'],
    ],
    //list_views
    'list_views' => [
        ['list_en' => 'nile', 'list_ar' => 'النيل'],
        ['list_en' => 'garden', 'list_ar' => 'الحديقة'],
        ['list_en' => 'main street', 'list_ar' => 'الشارع الرئيسي'],
        ['list_en' => 'side street', 'list_ar' => 'الشارع الجانبي'],
        ['list_en' => 'corner', 'list_ar' => 'الناصية'],
    ],
    // governorates
    'governorates' => [
        ['id' => 1, 'governorate_name_en' => 'Cairo', 'governorate_name_ar' => 'القاهرة'],
        ['id' => 2, 'governorate_name_en' => 'Giza', 'governorate_name_ar' => 'الجيزة'],
        ['id' => 3, 'governorate_name_en' => 'Alexandria', 'governorate_name_ar' => 'الأسكندرية'],
        ['id' => 4, 'governorate_name_en' => 'Dakahlia', 'governorate_name_ar' => 'الدقهلية'],
        ['id' => 5, 'governorate_name_en' => 'Red Sea', 'governorate_name_ar' => 'البحر الأحمر'],
        ['id' => 6, 'governorate_name_en' => 'Beheira', 'governorate_name_ar' => 'البحيرة'],
        ['id' => 7, 'governorate_name_en' => 'Fayoum', 'governorate_name_ar' => 'الفيوم'],
        ['id' => 8, 'governorate_name_en' => 'Gharbiya', 'governorate_name_ar' => 'الغربية'],
        ['id' => 9, 'governorate_name_en' => 'Ismailia', 'governorate_name_ar' => 'الإسماعلية'],
        ['id' => 10, 'governorate_name_en' => 'Monofia', 'governorate_name_ar' => 'المنوفية'],
        ['id' => 11, 'governorate_name_en' => 'Minya', 'governorate_name_ar' => 'المنيا'],
        ['id' => 12, 'governorate_name_en' => 'Qaliubiya', 'governorate_name_ar' => 'القليوبية'],
        ['id' => 13, 'governorate_name_en' => 'New Valley', 'governorate_name_ar' => 'الوادي الجديد'],
        ['id' => 14, 'governorate_name_en' => 'Suez', 'governorate_name_ar' => 'السويس'],
        ['id' => 15, 'governorate_name_en' => 'Aswan', 'governorate_name_ar' => 'اسوان'],
        ['id' => 16, 'governorate_name_en' => 'Assiut', 'governorate_name_ar' => 'اسيوط'],
        ['id' => 17, 'governorate_name_en' => 'Beni Suef', 'governorate_name_ar' => 'بني سويف'],
        ['id' => 18, 'governorate_name_en' => 'Port Said', 'governorate_name_ar' => 'بورسعيد'],
        ['id' => 19, 'governorate_name_en' => 'Damietta', 'governorate_name_ar' => 'دمياط'],
        ['id' => 20, 'governorate_name_en' => 'Sharkia', 'governorate_name_ar' => 'الشرقية'],
        ['id' => 21, 'governorate_name_en' => 'South Sinai', 'governorate_name_ar' => 'جنوب سيناء'],
        ['id' => 22, 'governorate_name_en' => 'Kafr Al sheikh', 'governorate_name_ar' => 'كفر الشيخ'],
        ['id' => 23, 'governorate_name_en' => 'Matrouh', 'governorate_name_ar' => 'مطروح'],
        ['id' => 24, 'governorate_name_en' => 'Luxor', 'governorate_name_ar' => 'الأقصر'],
        ['id' => 25, 'governorate_name_en' => 'Qena', 'governorate_name_ar' => 'قنا'],
        ['id' => 26, 'governorate_name_en' => 'North Sinai', 'governorate_name_ar' => 'شمال سيناء'],
        ['id' => 27, 'governorate_name_en' => 'Sohag', 'governorate_name_ar' => 'سوهاج'],
    ],
    //cities
    'cities' => [
        ['id' => 1, 'city_name_en' => 'Cairo', 'city_name_ar' => 'القاهره', 'gov_id' => 1],
        ['id' => 2, 'city_name_en' => 'Giza', 'city_name_ar' => 'الجيزة', 'gov_id' => 2],
        ['id' => 3, 'city_name_en' => 'Sixth of October', 'city_name_ar' => 'السادس من أكتوبر', 'gov_id' => 2],
        ['id' => 4, 'city_name_en' => 'Cheikh Zayed', 'city_name_ar' => 'الشيخ زايد', 'gov_id' => 2],
        ['id' => 5, 'city_name_en' => 'Hawamdiyah', 'city_name_ar' => 'الحوامدية', 'gov_id' => 2],
        ['id' => 6, 'city_name_en' => 'Al Badrasheen', 'city_name_ar' => 'البدرشين', 'gov_id' => 2],
        ['id' => 7, 'city_name_en' => 'Saf', 'city_name_ar' => 'الصف', 'gov_id' => 2],
        ['id' => 8, 'city_name_en' => 'Atfih', 'city_name_ar' => 'أطفيح', 'gov_id' => 2],
        ['id' => 9, 'city_name_en' => 'Al Ayat', 'city_name_ar' => 'العياط', 'gov_id' => 2],
        ['id' => 10, 'city_name_en' => 'Al-Bawaiti', 'city_name_ar' => 'الباويطي', 'gov_id' => 2],
        ['id' => 11, 'city_name_en' => 'ManshiyetAl Qanater', 'city_name_ar' => 'منشأة القناطر', 'gov_id' => 2],
        ['id' => 12, 'city_name_en' => 'Oaseem', 'city_name_ar' => 'أوسيم', 'gov_id' => 2],
        ['id' => 13, 'city_name_en' => 'Kerdasa', 'city_name_ar' => 'كرداسة', 'gov_id' => 2],
        ['id' => 14, 'city_name_en' => 'Abu Nomros', 'city_name_ar' => 'أبو النمرس', 'gov_id' => 2],
        ['id' => 15, 'city_name_en' => 'Kafr Ghati', 'city_name_ar' => 'كفر غطاطي', 'gov_id' => 2],
        ['id' => 16, 'city_name_en' => 'Manshiyet Al Bakari', 'city_name_ar' => 'منشأة البكاري', 'gov_id' => 2],
        ['id' => 17, 'city_name_en' => 'Alexandria', 'city_name_ar' => 'الأسكندرية', 'gov_id' => 3],
        ['id' => 18, 'city_name_en' => 'Burj Al Arab', 'city_name_ar' => 'برج العرب', 'gov_id' => 3],
        ['id' => 19, 'city_name_en' => 'New Burj Al Arab', 'city_name_ar' => 'برج العرب الجديدة', 'gov_id' => 3],
        ['id' => 20, 'city_name_en' => 'Banha', 'city_name_ar' => 'بنها', 'gov_id' => 12],
        ['id' => 21, 'city_name_en' => 'Qalyub', 'city_name_ar' => 'قليوب', 'gov_id' => 12],
        ['id' => 22, 'city_name_en' => 'Shubra Al Khaimah', 'city_name_ar' => 'شبرا الخيمة', 'gov_id' => 12],
        ['id' => 23, 'city_name_en' => 'Al Qanater Charity', 'city_name_ar' => 'القناطر الخيرية', 'gov_id' => 12],
        ['id' => 24, 'city_name_en' => 'Khanka', 'city_name_ar' => 'الخانكة', 'gov_id' => 12],
        ['id' => 25, 'city_name_en' => 'Kafr Shukr', 'city_name_ar' => 'كفر شكر', 'gov_id' => 12],
        ['id' => 26, 'city_name_en' => 'Tukh', 'city_name_ar' => 'طوخ', 'gov_id' => 12],
        ['id' => 27, 'city_name_en' => 'Qaha', 'city_name_ar' => 'قها', 'gov_id' => 12],
        ['id' => 28, 'city_name_en' => 'Obour', 'city_name_ar' => 'العبور', 'gov_id' => 12],
        ['id' => 29, 'city_name_en' => 'Khosous', 'city_name_ar' => 'الخصوص', 'gov_id' => 12],
        ['id' => 30, 'city_name_en' => 'Shibin Al Qanater', 'city_name_ar' => 'شبين القناطر', 'gov_id' => 12],
        ['id' => 31, 'city_name_en' => 'Damanhour', 'city_name_ar' => 'دمنهور', 'gov_id' => 6],
        ['id' => 32, 'city_name_en' => "Kafr El Dawar", "city_name_ar" =>'كفر الدوار', "gov_id" =>'6'],
        ['id'=>33,'city_name_en'=>'Rashid','city_name_ar'=>'رشيد','gov_id'=>6],
        ['id'=>34,'city_name_en'=>'Edco','city_name_ar'=>'إدكو','gov_id'=>6],
        ['id'=>35,'city_name_en'=>'Abu al-Matamir','city_name_ar'=>'أبو المطامير','gov_id'=>6],
        ['id'=>36,'city_name_en'=>'Abu Homs','city_name_ar'=>'أبو حمص','gov_id'=>6],
        ['id'=>37,'city_name_en'=>'Delengat','city_name_ar'=>'الدلنجات','gov_id'=>6],
        ['id'=>38,'city_name_en'=>'Mahmoudiyah','city_name_ar'=>'المحمودية','gov_id'=>6],
        ['id'=>39,'city_name_en'=>'Rahmaniyah','city_name_ar'=>'الرحمانية','gov_id'=>6],
        ['id'=>40,'city_name_en'=>'Itai Baroud','city_name_ar'=>'إيتاي البارود','gov_id'=>6],
        ['id'=>41,'city_name_en'=>'Housh Eissa','city_name_ar'=>'حوش عيسى','gov_id'=>6],
        ['id'=>42,'city_name_en'=>'Shubrakhit','city_name_ar'=>'شبراخيت','gov_id'=>6],
        ['id'=>43,'city_name_en'=>'Kom Hamada','city_name_ar'=>'كوم حمادة','gov_id'=>6],
        ['id'=>44,'city_name_en'=>'Badr','city_name_ar'=>'بدر','gov_id'=>6],
        ['id'=>45,'city_name_en'=>'Wadi Natrun','city_name_ar'=>'وادي النطرون','gov_id'=>6],
        ['id'=>46,'city_name_en'=>'New Nubaria','city_name_ar'=>'النوبارية الجديدة','gov_id'=>6],
        ['id'=>47,'city_name_en'=>'Marsa Matrouh','city_name_ar'=>'مرسى مطروح','gov_id'=>23],
        ['id'=>48,'city_name_en'=>'El Hamam','city_name_ar'=>'الحمام','gov_id'=>23],
        ['id'=>49,'city_name_en'=>'Alamein','city_name_ar'=>'العلمين','gov_id'=>23],
        ['id'=>50,'city_name_en'=>'Dabaa','city_name_ar'=>'الضبعة','gov_id'=>23],
        ['id'=>51,'city_name_en'=>'Al-Nagila','city_name_ar'=>'النجيلة','gov_id'=>23],
        ['id'=>52,'city_name_en'=>'Sidi Brani','city_name_ar'=>'سيدي براني','gov_id'=>23],
        ['id'=>53,'city_name_en'=>'Salloum','city_name_ar'=>'السلوم','gov_id'=>23],
        ['id'=>54,'city_name_en'=>'Siwa','city_name_ar'=>'سيوة','gov_id'=>23],
        ['id'=>55,'city_name_en'=>'Damietta', 'city_name_ar' => 'دمياط', 'gov_id' => 19],
        ['id' => 56, 'city_name_en' => 'New Damietta', 'city_name_ar' => 'دمياط الجديدة', 'gov_id' => 19],
        ['id' => 57, 'city_name_en' => 'Ras El Bar', 'city_name_ar' => 'رأس البر', 'gov_id' => 19],
        ['id' => 58, 'city_name_en' => 'Faraskour', 'city_name_ar' => 'فارسكور', 'gov_id' => 19],
        ['id' => 59, 'city_name_en' => 'Zarqa', 'city_name_ar' => 'الزرقا', 'gov_id' => 19],
        ['id' => 60, 'city_name_en' => 'alsaru', 'city_name_ar' => 'السرو', 'gov_id' => 19],
        ['id' => 61, 'city_name_en' => 'alruwda', 'city_name_ar' => 'الروضة', 'gov_id' => 19],
        ['id' => 62, 'city_name_en' => "Kafr El-Batikh", "city_name_ar"=> 'كفر البطيخ', "gov_id" => 19],
        ['id' => 63, 'city_name_en' => 'Azbet Al Burg', 'city_name_ar' => 'عزبة البرج', 'gov_id' => 19],
        ['id' => 64, 'city_name_en' => 'Meet Abou Ghalib', 'city_name_ar' => 'ميت أبو غالب', 'gov_id' => 19],
        ['id' => 65, 'city_name_en' => 'Kafr Saad', 'city_name_ar' => 'كفر سعد', 'gov_id' => 19],
        ['id' => 66, 'city_name_en' => 'Mansoura', 'city_name_ar' => 'المنصورة', 'gov_id' => 4],
        ['id' => 67, 'city_name_en' => 'Talkha', 'city_name_ar' => 'طلخا', 'gov_id' => 4],
        ['id' => 68, 'city_name_en' => 'Mitt Ghamr', 'city_name_ar' => 'ميت غمر', 'gov_id' => 4],
        ['id' => 69, 'city_name_en' => 'Dekernes', 'city_name_ar' => 'دكرنس', 'gov_id' => 4],
        ['id' => 70, 'city_name_en' => "Aga", "city_name_ar" =>'أجا', "gov_id" =>'4'],
        ['id'=>71,'city_name_en'=>'Menia El Nasr','city_name_ar'=>'منية النصر','gov_id'=>4],
        ['id'=>72,'city_name_en'=>'Sinbillawin','city_name_ar'=>'السنبلاوين','gov_id'=>4],
        ['id'=>73,'city_name_en'=>'El Kurdi','city_name_ar'=>'الكردي','gov_id'=>4],
        ['id'=>74,'city_name_en'=>'Bani Ubaid','city_name_ar'=>'بني عبيد','gov_id'=>4],
        ['id'=>75,'city_name_en'=>'Al Manzala','city_name_ar'=>'المنزلة','gov_id'=>4],
        ['id'=>76,'city_name_en'=>'tami al\'amdid','city_name_ar'=>'تمي الأمديد','gov_id'=>4],
        ['id'=>77,'city_name_en'=>'aljamalia','city_name_ar'=>'الجمالية','gov_id'=>4],
        ['id'=>78,'city_name_en'=>'Sherbin','city_name_ar'=>'شربين','gov_id'=>4],
        ['id'=>79,'city_name_en'=>'Mataria','city_name_ar'=>'المطرية','gov_id'=>4],
        ['id'=>80,'city_name_en'=>'Belqas','city_name_ar'=>'بلقاس','gov_id'=>4],
        ['id'=>81,'city_name_en'=>'Meet Salsil','city_name_ar'=>'ميت سلسيل','gov_id'=>4],
        ['id'=>82,'city_name_en'=>'Gamasa','city_name_ar'=>'جمصة','gov_id'=>4],
        ['id'=>83,'city_name_en'=>'Mahalat Damana','city_name_ar'=>'محلة دمنة','gov_id'=>4],
        ['id'=>84,'city_name_en'=>'Nabroh','city_name_ar'=>'نبروه','gov_id'=>4],
        ['id' => 85, 'city_name_en' => 'Kafr El Sheikh', 'city_name_ar' => 'كفر الشيخ', 'gov_id' => 22],
        ['id' => 86, 'city_name_en' => 'Desouq', 'city_name_ar' => 'دسوق', 'gov_id' => 22],
        ['id' => 87, 'city_name_en' => 'Fooh', 'city_name_ar' => 'فوه', 'gov_id' => 22],
        ['id' => 88, 'city_name_en' => 'Metobas', 'city_name_ar' => 'مطوبس', 'gov_id' => 22],
        ['id' => 89, 'city_name_en' => 'Burg Al Burullus', 'city_name_ar' => 'برج البرلس', 'gov_id' => 22],
        ['id' => 90, 'city_name_en' => 'Baltim', 'city_name_ar' => 'بلطيم', 'gov_id' => 22],
        ['id' => 91, 'city_name_en' => 'Masief Baltim', 'city_name_ar' => 'مصيف بلطيم', 'gov_id' => 22],
        ['id' => 92, 'city_name_en' => "Hamol", "city_name_ar" =>'الحامول', "gov_id" =>'22'],
        ['id'=>93,'city_name_en'=>'Bella','city_name_ar'=>'بيلا','gov_id'=>22],
        ['id'=>94,'city_name_en'=>'Riyadh','city_name_ar'=>'الرياض','gov_id'=>22],
        ['id'=>95,'city_name_en'=>'Sidi Salm','city_name_ar'=>'سيدي سالم','gov_id'=>22],
        ['id'=>96,'city_name_en'=>'Qellen','city_name_ar'=>'قلين','gov_id'=>22],
        ['id'=>97,'city_name_en'=>'Sidi Ghazi','city_name_ar'=>'سيدي غازي','gov_id'=>22],
        ['id' => 98, 'city_name_en' => 'Tanta', 'city_name_ar' => 'طنطا', 'gov_id' => 8],
        ['id' => 99, 'city_name_en' => 'Al Mahalla Al Kobra', 'city_name_ar' => 'المحلة الكبرى', 'gov_id' => 8],
        ['id' => 100, 'city_name_en' => 'Kafr El Zayat', 'city_name_ar' => 'كفر الزيات', 'gov_id' => 8],
        ['id' => 101, 'city_name_en' => 'Zefta', 'city_name_ar' => 'زفتى', 'gov_id' => 8],
        ['id' => 102, 'city_name_en' => 'El Santa', 'city_name_ar' => 'السنطة', 'gov_id' => 8],
        ['id' => 103, 'city_name_en' => "Qutour", "city_name_ar" =>'قطور', "gov_id" =>'8'],
        ['id'=>104,'city_name_en'=>'Basion','city_name_ar'=>'بسيون','gov_id'=>8],
        ['id'=>105,'city_name_en'=>'Samannoud','city_name_ar'=>'سمنود','gov_id'=>8],
        ['id'=>106,'city_name_en'=>'Shbeen El Koom','city_name_ar'=>'شبين الكوم','gov_id'=>10],
        ['id'=>107,'city_name_en'=>'Sadat City','city_name_ar'=>'مدينة السادات','gov_id'=>10],
        ['id'=>108,'city_name_en'=>'Menouf','city_name_ar'=>'منوف','gov_id'=>10],
        ['id'=>109,'city_name_en'=>'Sars El-Layan','city_name_ar'=>'سرس الليان','gov_id'=>10],
        ['id'=>110,'city_name_en'=>'Ashmon','city_name_ar'=>'أشمون','gov_id'=>10],
        ['id'=>111,'city_name_en'=>'Al Bagor','city_name_ar'=>'الباجور','gov_id'=>10],
        ['id'=>112,'city_name_en'=>'Quesna','city_name_ar'=>'قويسنا','gov_id'=>10],
        ['id'=>113,'city_name_en'=>'Berkat El Saba','city_name_ar'=>'بركة السبع','gov_id'=>10],
        ['id'=>114,'city_name_en'=>'Tala','city_name_ar'=>'تلا','gov_id'=>10],
        ['id'=>115,'city_name_en'=>'Al Shohada','city_name_ar'=>'الشهداء','gov_id'=>10],
        ['id' => 116, 'city_name_en' => 'Zagazig', 'city_name_ar' => 'الزقازيق', 'gov_id' => 20],
        ['id' => 117, 'city_name_en' => 'Al Ashr Men Ramadan', 'city_name_ar' => 'العاشر من رمضان', 'gov_id' => 20],
        ['id' => 118, 'city_name_en' => 'Minya Al Qamh', 'city_name_ar' => 'منيا القمح', 'gov_id' => 20],
        ['id' => 119, 'city_name_en' => 'Belbeis', 'city_name_ar' => 'بلبيس', 'gov_id' => 20],
        ['id' => 120, 'city_name_en' => 'Mashtoul El Souq', 'city_name_ar' => 'مشتول السوق', 'gov_id' => 20],
        ['id' => 121, 'city_name_en' => "Qenaiat", "city_name_ar" =>'القنايات', "gov_id" =>'20'],
        ['id'=>122,'city_name_en'=>'Abu Hammad','city_name_ar'=>'أبو حماد','gov_id'=>20],
        ['id'=>123,'city_name_en'=>'El Qurain','city_name_ar'=>'القرين','gov_id'=>20],
        ['id'=>124,'city_name_en'=>'Hehia','city_name_ar'=>'ههيا','gov_id'=>20],
        ['id'=>125,'city_name_en'=>'Abu Kabir','city_name_ar'=>'أبو كبير','gov_id'=>20],
        ['id'=>126,'city_name_en'=>'Faccus','city_name_ar'=>'فاقوس','gov_id'=>20],
        ['id'=>127,'city_name_en'=>'El Salihia El Gedida','city_name_ar'=>'الصالحية الجديدة','gov_id'=>20],
        ['id'=>128,'city_name_en'=>'Al Ibrahimiyah','city_name_ar'=>'الإبراهيمية','gov_id'=>20],
        ['id'=>129,'city_name_en'=>'Deirb Negm','city_name_ar'=>'ديرب نجم','gov_id'=>20],
        ['id'=>130,'city_name_en'=>'Kafr Saqr','city_name_ar'=>'كفر صقر','gov_id'=>20],
        ['id'=>131,'city_name_en'=>'Awlad Saqr','city_name_ar'=>'أولاد صقر','gov_id'=>20],
        ['id'=>132,'city_name_en'=>'Husseiniya','city_name_ar'=>'الحسينية','gov_id'=>20],
        ['id'=>133,'city_name_en'=>'san alhajar alqablia','city_name_ar'=>'صان الحجر القبلية','gov_id'=>20],
        ['id'=>134,'city_name_en'=>'Manshayat Abu Omar','city_name_ar'=>'منشأة أبو عمر','gov_id'=>20],
        ['id' => 135, 'city_name_en' => 'PorSaid', 'city_name_ar' => 'بورسعيد', 'gov_id' => 18],
        ['id' => 136, 'city_name_en' => 'PorFouad', 'city_name_ar' => 'بورفؤاد', 'gov_id' => 18],
        ['id' => 137, 'city_name_en' => 'Ismailia', 'city_name_ar' => 'الإسماعيلية', 'gov_id' => 9],
        ['id' => 138, 'city_name_en' => 'Fayed', 'city_name_ar' => 'فايد', 'gov_id' => 9],
        ['id' => 139, 'city_name_en' => "Qantara Sharq", "city_name_ar" =>'القنطرة شرق', "gov_id" =>'9'],
        ['id'=>140,'city_name_en'=>'Qantara Gharb','city_name_ar'=>'القنطرة غرب','gov_id'=>9],
        ['id'=>141,'city_name_en'=>'El Tal El Kabier','city_name_ar'=>'التل الكبير','gov_id'=>9],
        ['id'=>142,'city_name_en'=>'Abu Sawir','city_name_ar'=>'أبو صوير','gov_id'=>9],
        ['id'=>143,'city_name_en'=>'Kasasien El Gedida','city_name_ar'=>'القصاصين الجديدة','gov_id'=>9],
        ['id' => 144, 'city_name_en' => 'Suez', 'city_name_ar' => 'السويس', 'gov_id' => 14],
        ['id' => 145, 'city_name_en' => 'Arish', 'city_name_ar' => 'العريش', 'gov_id' => 26],
        ['id' => 146, 'city_name_en' => 'Sheikh Zowaid', 'city_name_ar' => 'الشيخ زويد', 'gov_id' => 26],
        ['id' => 147, 'city_name_en' => 'Nakhl', 'city_name_ar' => 'نخل', 'gov_id' => 26],
        ['id' => 148, 'city_name_en' => 'Rafah', 'city_name_ar' => 'رفح', 'gov_id' => 26],
        ['id' => 149, 'city_name_en' => 'Bir al-Abed', 'city_name_ar' => 'بئر العبد', 'gov_id' => 26],
        ['id' => 150, 'city_name_en' => 'Al Hasana', 'city_name_ar' => 'الحسنة', 'gov_id' => 26],
        ['id' => 151, 'city_name_en' => "Al Toor", "city_name_ar" =>'الطور', "gov_id" =>'21'],
        ['id'=>152,'city_name_en'=>'Sharm El-Shaikh','city_name_ar'=>'شرم الشيخ','gov_id'=>21],
        ['id'=>153,'city_name_en'=>'Dahab','city_name_ar'=>'دهب','gov_id'=>21],
        ['id'=>154,'city_name_en'=>'Nuweiba','city_name_ar'=>'نويبع','gov_id'=>21],
        ['id'=>155,'city_name_en'=>'Taba','city_name_ar'=>'طابا','gov_id'=>21],
        ['id'=>156,'city_name_en'=>'Saint Catherine','city_name_ar'=>'سانت كاترين','gov_id'=>21],
        ['id'=>157,'city_name_en'=>'Abu Redis','city_name_ar'=>'أبو رديس','gov_id'=>21],
        ['id'=>158,'city_name_en'=>'Abu Zenaima','city_name_ar'=>'أبو زنيمة','gov_id'=>21],
        ['id'=>159,'city_name_en'=>'Ras Sidr','city_name_ar'=>'رأس سدر','gov_id'=>21],
        ['id' => 160, 'city_name_en' => "Bani Sweif", "city_name_ar" =>'بني سويف', "gov_id" =>'17'],
        ['id'=>161,'city_name_en'=>'Beni Suef El Gedida','city_name_ar'=>'بني سويف الجديدة','gov_id'=>17],
        ['id'=>162,'city_name_en'=>'Al Wasta','city_name_ar'=>'الواسطى','gov_id'=>17],
        ['id'=>163,'city_name_en'=>'Naser','city_name_ar'=>'ناصر','gov_id'=>17],
        ['id'=>164,'city_name_en'=>'Ehnasia','city_name_ar'=>'إهناسيا','gov_id'=>17],
        ['id'=>165,'city_name_en'=>'beba','city_name_ar'=>'ببا','gov_id'=>17],
        ['id'=>166,'city_name_en'=>'Fashn','city_name_ar'=>'الفشن','gov_id'=>17],
        ['id'=>167,'city_name_en'=>'Somasta','city_name_ar'=>'سمسطا','gov_id'=>17],
        ['id' => 168, 'city_name_en' => 'Fayoum', 'city_name_ar' => 'الفيوم', 'gov_id' => 7],
        ['id' => 169, 'city_name_en' => 'Fayoum El Gedida', 'city_name_ar' => 'الفيوم الجديدة', 'gov_id' => 7],
        ['id' => 170, 'city_name_en' => 'Tamiya', 'city_name_ar' => 'طامية', 'gov_id' => 7],
        ['id' => 171, 'city_name_en' => 'Snores', 'city_name_ar' => 'سنورس', 'gov_id' => 7],
        ['id' => 172, 'city_name_en' => "Etsa", "city_name_ar" =>'إطسا', "gov_id" =>'7'],
        ['id'=>173,'city_name_en'=>'Epschway','city_name_ar'=>'إبشواي','gov_id'=>7],
        ['id'=>174,'city_name_en'=>'Yusuf El Sediaq','city_name_ar'=>'يوسف الصديق','gov_id'=>7],
        ['id'=>175,'city_name_en'=>'Minya','city_name_ar'=>'المنيا','gov_id'=>11],
        ['id'=>176,'city_name_en'=>'Minya El Gedida','city_name_ar'=>'المنيا الجديدة','gov_id'=>11],
        ['id'=>177,'city_name_en'=>'El Adwa','city_name_ar'=>'العدوة','gov_id'=>11],
        ['id'=>178,'city_name_en'=>'Magagha','city_name_ar'=>'مغاغة','gov_id'=>11],
        ['id'=>179,'city_name_en'=>'Bani Mazar','city_name_ar'=>'بني مزار','gov_id'=>11],
        ['id'=>180,'city_name_en'=>'Mattay','city_name_ar'=>'مطاي','gov_id'=>11],
        ['id'=>181,'city_name_en'=>'Samalut','city_name_ar'=>'سمالوط','gov_id'=>11],
        ['id'=>182,'city_name_en'=>'Madinat El Fekria','city_name_ar'=>'المدينة الفكرية','gov_id'=>11],
        ['id'=>183,'city_name_en'=>'Meloy','city_name_ar'=>'ملوي','gov_id'=>11],
        ['id'=>184,'city_name_en'=>'Deir Mawas','city_name_ar'=>'دير مواس','gov_id'=>11],
        ['id' => 185, 'city_name_en' => 'Assiut', 'city_name_ar' => 'أسيوط', 'gov_id' => 16],
        ['id' => 186, 'city_name_en' => 'Assiut El Gedida', 'city_name_ar' => 'أسيوط الجديدة', 'gov_id' => 16],
        ['id' => 187, 'city_name_en' => 'Dayrout', 'city_name_ar' => 'ديروط', 'gov_id' => 16],
        ['id' => 188, 'city_name_en' => 'Manfalut', 'city_name_ar' => 'منفلوط', 'gov_id' => 16],
        ['id' => 189, 'city_name_en' => "Qusiya", "city_name_ar" =>'القوصية', "gov_id" =>'16'],
        ['id'=>190,'city_name_en'=>'Abnoub','city_name_ar'=>'أبنوب','gov_id'=>16],
        ['id'=>191,'city_name_en'=>'Abu Tig','city_name_ar'=>'أبو تيج','gov_id'=>16],
        ['id'=>192,'city_name_en'=>'El Ghanaim','city_name_ar'=>'الغنايم','gov_id'=>16],
        ['id'=>193,'city_name_en'=>'Sahel Selim','city_name_ar'=>'ساحل سليم','gov_id'=>16],
        ['id'=>194,'city_name_en'=>'El Badari','city_name_ar'=>'البداري','gov_id'=>16],
        ['id'=>195,'city_name_en'=>'Sidfa','city_name_ar'=>'صدفا','gov_id'=>16],
        ['id' => 196, 'city_name_en' => 'El Kharga', 'city_name_ar' => 'الخارجة', 'gov_id' => 13],
        ['id' => 197, 'city_name_en' => 'Paris', 'city_name_ar' => 'باريس', 'gov_id' => 13],
        ['id' => 198, 'city_name_en' => 'Mout', 'city_name_ar' => 'موط', 'gov_id' => 13],
        ['id' => 199, 'city_name_en' => 'Farafra', 'city_name_ar' => 'الفرافرة', 'gov_id' => 13],
        ['id' => 200, 'city_name_en' => 'Balat', 'city_name_ar' => 'بلاط', 'gov_id' => 13],
        ['id' => 201, 'city_name_en' => 'Hurghada', 'city_name_ar' => 'الغردقة', 'gov_id' => 5],
        ['id' => 202, 'city_name_en' => "Ras Ghareb", "city_name_ar" =>'رأس غارب', "gov_id" =>'5'],
        ['id'=>203,'city_name_en'=>'Safaga','city_name_ar'=>'سفاجا','gov_id'=>5],
        ['id'=>204,'city_name_en'=>'El Qusiar','city_name_ar'=>'القصير','gov_id'=>5],
        ['id'=>205,'city_name_en'=>'Marsa Alam','city_name_ar'=>'مرسى علم','gov_id'=>5],
        ['id'=>206,'city_name_en'=>'Shalatin','city_name_ar'=>'الشلاتين','gov_id'=>5],
        ['id'=>207,'city_name_en'=>'Halaib','city_name_ar'=>'حلايب','gov_id'=>5],
        ['id'=>208,'city_name_en'=>'Sohag','city_name_ar'=>'سوهاج','gov_id'=>27],
        ['id'=>209,'city_name_en'=>'Sohag El Gedida', 'city_name_ar' => 'سوهاج الجديدة', 'gov_id' => 27],
        ['id'=>210,'city_name_en'=>'Akhmeem','city_name_ar'=>'أخميم','gov_id'=>27],
        ['id'=>211,'city_name_en'=>'Akhmim El Gedida','city_name_ar'=>'أخميم الجديدة','gov_id'=>27],
        ['id'=>212,'city_name_en'=>'Albalina','city_name_ar' =>'البلينا','gov_id'=>27],
        ['id'=>213,'city_name_en'=>'Juhayna','city_name_ar'=>'جهينة','gov_id'=>27],
        ['id'=>214,'city_name_en'=>'Tahta','city_name_ar'=>'طهطا','gov_id'=>27],
        ['id'=>215,'city_name_en'=>'Gerga','city_name_ar'=>'جرجا','gov_id'=>27],
        ['id'=>216,'city_name_en'=>'El Maragha','city_name_ar'=>'المراغة','gov_id'=>27],
        ['id'=>217,'city_name_en'=>'El Qawz','city_name_ar'=>'القوصية','gov_id'=>27],
        ['id'=>218,'city_name_en'=>'Dar El Salam','city_name_ar'=>'دار السلام','gov_id'=>27],
        ['id'=>219,'city_name_en'=>'Al Balina','city_name_ar'=>'البلينا','gov_id'=>27],
        ['id' => 220, 'city_name_en' => 'Qena', 'city_name_ar' => 'قنا', 'gov_id' => 25],
        ['id' => 221, 'city_name_en' => 'Qena El Gedida', 'city_name_ar' => 'قنا الجديدة', 'gov_id' => 25],
        ['id' => 222, 'city_name_en' => 'Nag Hammadi', 'city_name_ar' => 'نجع حمادي', 'gov_id' => 25],
        ['id' => 223, 'city_name_en' => "Deshna", "city_name_ar" =>'دشنا', "gov_id" =>'25'],
        ['id'=>224,'city_name_en'=>'Qift','city_name_ar'=>'قفط','gov_id'=>25],
        ['id'=>225,'city_name_en'=>'Farshout','city_name_ar'=>'فرشوط','gov_id'=>25],
        ['id'=>226,'city_name_en'=>'Abu Tesht','city_name_ar'=>'أبو تشت','gov_id'=>25],
        ['id'=>227,'city_name_en'=>'Kous','city_name_ar'=>'قوص','gov_id'=>25],
        ['id'=>228,'city_name_en'=>'Naga Hammadi El Gedida','city_name_ar'=>'نجع حمادي الجديدة','gov_id'=>25],
        ['id' => 229, 'city_name_en' => 'Luxor', 'city_name_ar' => 'الأقصر', 'gov_id' => 15],
        ['id' => 230, 'city_name_en' => 'Luxor El Gedida', 'city_name_ar' => 'الأقصر الجديدة', 'gov_id' => 15],
        ['id' => 231, 'city_name_en' => 'Esna', 'city_name_ar' => 'إسنا', 'gov_id' => 15],
        ['id' => 232, 'city_name_en' => "Armant", "city_name_ar" =>'أرمنت', "gov_id" =>'15'],
        ['id'=>233,'city_name_en'=>'Tiba','city_name_ar'=>'طيبة','gov_id'=>15],
        ['id'=>234,'city_name_en'=>'Al Zaytounah','city_name_ar'=>'الزيتونة','gov_id'=>15],
        ['id'=>235,'city_name_en'=>'Al Qarnah','city_name_ar'=>'القرنة','gov_id'=>15],
        ['id'=>236,'city_name_en'=>'Al Waqf','city_name_ar'=>'الوقف','gov_id'=>15],
        ['id' => 237, 'city_name_en' => 'Aswan', 'city_name_ar' => 'أسوان', 'gov_id' => 24],
        ['id' => 238, 'city_name_en' => "Aswan El Gedida", "city_name_ar" =>'أسوان الجديدة', "gov_id" =>'24'],
        ['id'=>239,'city_name_en'=>'Nasser City Aswan','city_name_ar'=>'مدينة ناصر أسوان','gov_id'=>24],
        ['id'=>240,'city_name_en'=>'Kom Ombo','city_name_ar'=>'كوم أمبو','gov_id'=>24],
        ['id'=>241,'city_name_en'=>'Daraw','city_name_ar'=>'دروا','gov_id'=>24],
        ['id'=>242,'city_name_en'=>'Edfu','city_name_ar'=>'إدفو','gov_id'=>24],
        ['id'=>243,'city_name_en'=>'Aswan El Gedida','city_name_ar'=>'أسوان الجديدة','gov_id'=>24],
        ['id' => 244, 'city_name_en' => 'Matrouh', 'city_name_ar' => 'مطروح', 'gov_id' => 23],
        ['id' => 245, 'city_name_en' => 'Al Hamam', 'city_name_ar' => 'الحمام', 'gov_id' => 23],
        ['id' => 246, 'city_name_en' => "Alamein", "city_name_ar" =>'العلمين', "gov_id" =>'23'],
        ['id'=>247,'city_name_en'=>'Dabaa','city_name_ar'=>'الضبعة','gov_id'=>23],
        ['id'=>248,'city_name_en'=>'Al-Nagila','city_name_ar'=>'النجيلة','gov_id'=>23],
        ['id'=>249,'city_name_en'=>'Sidi Brani','city_name_ar'=>'سيدي براني','gov_id'=>23],
        ['id'=>250,'city_name_en'=>'Salloum','city_name_ar'=>'السلوم','gov_id'=>23],
    ],
];